name: CI Pipeline - DevSecOps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker image and run linters
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t devsecops-api .

    - name: Install hadolint (Dockerfile linter)
      run: |
        wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        chmod +x /bin/hadolint

    - name: Lint Dockerfile
      run: hadolint Dockerfile

    - name: Install yamllint
      run: sudo apt-get update && sudo apt-get install -y yamllint

    - name: Lint YAML files
      run: |
        find . -name "*.yaml" -o -name "*.yml" | xargs yamllint

